name: Slack Server Deployment (Production)

on:
  push:
    branches: [ master ]

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_MSP_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # 디렉토리 이동
            cd ~/k8s-aws

            # 백업 생성
            timestamp=$(date +%Y%m%d_%H%M%S)
            if [ -f mcp/.pid/slack_server.pid ]; then
              cp mcp/logs/slack_server.log mcp/logs/slack_server_${timestamp}.log
            fi

            # 기존 프로세스 정리
            if [ -f mcp/.pid/slack_server.pid ]; then
              pid=$(cat mcp/.pid/slack_server.pid)
              if ps -p $pid > /dev/null; then
                kill $pid
                echo "Stopped existing Slack server (PID: $pid)"
              fi
            fi

            # 로컬 변경사항 저장
            cd mcp
            git stash

            # 최신 코드 가져오기
            git fetch origin master
            git checkout master
            git pull origin master

            # 필요한 디렉토리 생성
            mkdir -p .pid logs

            # 환경 변수 설정
            export SLACK_SIGNING_SECRET="${{ secrets.SLACK_SIGNING_SECRET }}"
            export FLASK_ENV="production"

            # 서버 시작 (절대 경로 사용)
            cd ~/k8s-aws/mcp/workflows
            python3 -m slack_server > ~/k8s-aws/mcp/logs/slack_server.log 2>&1 &
            echo $! > ~/k8s-aws/mcp/.pid/slack_server.pid

            # 서버 상태 확인 (절대 경로 사용)
            sleep 10
            if ps -p $(cat ~/k8s-aws/mcp/.pid/slack_server.pid) > /dev/null; then
              echo "Slack server started successfully"
              exit 0
            else
              echo "Failed to start Slack server"
              tail -n 20 ~/k8s-aws/mcp/logs/slack_server.log
              exit 1
            fi

      - name: Verify Deployment
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_MSP_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # 프로세스 상태 확인 (절대 경로 사용)
            if [ ! -f ~/k8s-aws/mcp/.pid/slack_server.pid ] || ! ps -p $(cat ~/k8s-aws/mcp/.pid/slack_server.pid) > /dev/null; then
              echo "Slack server is not running"
              tail -n 20 ~/k8s-aws/mcp/logs/slack_server.log
              exit 1
            fi

            # 헬스 체크
            for i in {1..3}; do
              if curl -s http://localhost:8081/health; then
                echo "Health check passed"
                exit 0
              fi
              sleep 5
            done
            
            echo "Health check failed after 3 attempts"
            tail -n 20 ~/k8s-aws/mcp/logs/slack_server.log
            exit 1 